/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p17.reto4.vista;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import utp.misiontic2022.c2.p17.reto4.controlador.ControladorRequerimientos;
import utp.misiontic2022.c2.p17.reto4.modelo.vo.Requerimiento_1;
import utp.misiontic2022.c2.p17.reto4.modelo.vo.Requerimiento_2;
import utp.misiontic2022.c2.p17.reto4.modelo.vo.Requerimiento_3;

/**
 *
 * @author Didier Andres LLanten Velez
 */
public class ProyectosConstruccion_GUI extends javax.swing.JFrame {

    private ControladorRequerimientos controladorRequerimientos;
    private LideresTM lideresTM;
    private MaterialesTM materialesTM;
    private ProyectosTM proyectosTM;

    public ProyectosConstruccion_GUI() {
        initComponents();
        setLocationRelativeTo(null);
        controladorRequerimientos = new ControladorRequerimientos();
        cargarInfo();
    }

    private void cargarInfo() {
        try {
            //Cargar la lista de lideres en tbLideres
            ArrayList<Requerimiento_1> lideres = controladorRequerimientos.consultarRequerimiento1();
            lideresTM = new LideresTM(lideres);
            tbLideres.setModel(lideresTM);
            
            //Cargar la lista de materiales en tbMateriales
            ArrayList<Requerimiento_2> materiales = controladorRequerimientos.consultarRequerimiento2();
            materialesTM = new MaterialesTM(materiales);
            tbMateriales.setModel(materialesTM);
            
            //Cargar la lista de proyectos en tbProyectos
            ArrayList<Requerimiento_3> proyectos = controladorRequerimientos.consultarRequerimiento3();
            proyectosTM = new ProyectosTM(proyectos);
            tbProyectos.setModel(proyectosTM);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpPrincipal = new javax.swing.JTabbedPane();
        pLideres = new javax.swing.JPanel();
        ttLideres = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLideres = new javax.swing.JTable();
        pMateriales = new javax.swing.JPanel();
        ttMateriales = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMateriales = new javax.swing.JTable();
        pProyectos = new javax.swing.JPanel();
        ttProyectos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProyectos = new javax.swing.JTable();
        mbConstructionProyect = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();
        mWindow = new javax.swing.JMenu();
        miLideres = new javax.swing.JMenuItem();
        miMateriales = new javax.swing.JMenuItem();
        miProyectos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyectos de Construccion");

        pLideres.setLayout(new java.awt.BorderLayout());

        ttLideres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ttLideres.setText("Lideres");
        pLideres.add(ttLideres, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tbLideres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lider", "Cargo", "# Proyectos"
            }
        ));
        jScrollPane1.setViewportView(tbLideres);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pLideres.add(jPanel1, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Lideres", pLideres);

        pMateriales.setLayout(new java.awt.BorderLayout());

        ttMateriales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ttMateriales.setText("Materiales");
        pMateriales.add(ttMateriales, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tbMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Material", "Cantidad", "Precio unidad", "Precio Total"
            }
        ));
        jScrollPane2.setViewportView(tbMateriales);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pMateriales.add(jPanel2, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Materiales", pMateriales);

        pProyectos.setLayout(new java.awt.BorderLayout());

        ttProyectos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ttProyectos.setText("Proyectos");
        pProyectos.add(ttProyectos, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        tbProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ciudad", "Clasificacion", "Costo_Proyecto"
            }
        ));
        jScrollPane3.setViewportView(tbProyectos);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        pProyectos.add(jPanel3, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Proyectos", pProyectos);

        getContentPane().add(tpPrincipal, java.awt.BorderLayout.CENTER);

        mFile.setText("File");

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mFile.add(miExit);

        mbConstructionProyect.add(mFile);

        mWindow.setText("Window");

        miLideres.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miLideres.setText("Lideres");
        miLideres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLideresActionPerformed(evt);
            }
        });
        mWindow.add(miLideres);

        miMateriales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miMateriales.setText("Materiales");
        miMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMaterialesActionPerformed(evt);
            }
        });
        mWindow.add(miMateriales);

        miProyectos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miProyectos.setText("Proyectos");
        miProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProyectosActionPerformed(evt);
            }
        });
        mWindow.add(miProyectos);

        mbConstructionProyect.add(mWindow);

        setJMenuBar(mbConstructionProyect);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miLideresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLideresActionPerformed
        tpPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_miLideresActionPerformed

    private void miMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMaterialesActionPerformed
        tpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_miMaterialesActionPerformed

    private void miProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProyectosActionPerformed
        tpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_miProyectosActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Desea cerrar la aplicacion.", getTitle(), JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_miExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectosConstruccion_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectosConstruccion_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectosConstruccion_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectosConstruccion_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectosConstruccion_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mWindow;
    private javax.swing.JMenuBar mbConstructionProyect;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miLideres;
    private javax.swing.JMenuItem miMateriales;
    private javax.swing.JMenuItem miProyectos;
    private javax.swing.JPanel pLideres;
    private javax.swing.JPanel pMateriales;
    private javax.swing.JPanel pProyectos;
    private javax.swing.JTable tbLideres;
    private javax.swing.JTable tbMateriales;
    private javax.swing.JTable tbProyectos;
    private javax.swing.JTabbedPane tpPrincipal;
    private javax.swing.JLabel ttLideres;
    private javax.swing.JLabel ttMateriales;
    private javax.swing.JLabel ttProyectos;
    // End of variables declaration//GEN-END:variables

}
